<?php
	#basically this takes all the variables and settings from the config.php file, includes files needed and then manipulates the variables for use in the template (.tpl) file selected. No HTML is done in this file - please do this in a .tpl file.
	include('config.php');
	if($settings->first_run == 1){
		header("Location: admin/settings.php");
	   	exit;
	}

	include('lib/parsedown.php'); #convert markdown to pure HTML
	include('lib/parsedownextra.php'); #extra functions for parsedown
	include('lib/puppystats.php'); #PuppyStats
	require 'lib/pass.php'; #css preprocessor


	$site_title = $title ? $title : $default_title;
	$site_description = $meta_desc ? $meta_desc.'' : '';

	// Parsing the contents
	$Parsedown = new ParsedownExtra();
	$contents = $Parsedown->text($content);

	// Themes default stylesheet (style.css) which get generated by Pass
	$pass = new pass($site_template . '/style.txt');
	$theme_stylesheet = '<link rel="stylesheet" href="'.$pass->name.'">';

	// Including selected temeplate/theme's index.php to load the UI
	$theme_index = $site_template.'/index.php';
	include $theme_index;
?>